# Generated by Django 5.2 on 2025-04-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ZUser',
            fields=[
                ('zid', models.AutoField(primary_key=True, serialize=False)),
                ('id', models.CharField(max_length=150, unique=True)),
                ('name', models.CharField(max_length=150, unique=True)),
                ('password', models.CharField(max_length=128)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('inuse', models.BooleanField(default=True)),
                ('zcme', models.IntegerField()),
                ('zctm', models.DateTimeField(auto_now_add=True)),
                ('zcby', models.CharField(max_length=100)),
                ('zcat', models.CharField(max_length=300)),
                ('zcre', models.CharField(max_length=100)),
                ('zume', models.IntegerField()),
                ('zutm', models.DateTimeField(auto_now_add=True)),
                ('zuby', models.CharField(max_length=100)),
                ('zuat', models.CharField(max_length=300)),
                ('zure', models.CharField(max_length=100)),
            ],
        ),
    ]
