# Generated by Django 5.2 on 2025-04-15 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zuser',
            name='remark',
            field=models.CharField(default=' ', max_length=300),
        ),
    ]
