# Generated by Django 5.2 on 2025-04-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0002_zuser_remark'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='zuser',
            table='zuser',
        ),
    ]
