# Generated by Django 5.2 on 2025-04-15 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_alter_zuser_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuser',
            name='zcme',
            field=models.IntegerField(null=True),
        ),
    ]
