# Generated by Django 5.2 on 2025-04-15 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0004_alter_zuser_zcme'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zuser',
            old_name='date_joined',
            new_name='joined',
        ),
        migrations.AlterField(
            model_name='zuser',
            name='zcat',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='zcby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='zcre',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='zuat',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='zuby',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='zume',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='zuser',
            name='zure',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
