# Generated by Django 5.2 on 2025-04-15 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0005_rename_date_joined_zuser_joined_alter_zuser_zcat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zuser',
            name='name',
            field=models.CharField(max_length=150),
        ),
    ]
